export { ScrambleWordAdminComponent } from './scramble-word/scramble-word-admin/scramble-word-admin.component'
export { ScrambleWordControlComponent } from './scramble-word/scramble-word-control/scramble-word-control.component'
export { ScrambleWordLogicComponent } from './scramble-word/scramble-word-logic/scramble-word-logic.component'
export { ScrambleWordLogicOnethirdComponent } from './scramble-word/scramble-word-logic-onethird/scramble-word-logic-onethird.component'
export { QuestionListComponent } from './question-list/question-list.component'
export { MainTitleComponent } from './main-title/main-title.component'
export { ComponentModule } from './component.module'
